# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/brendel/dev/games/LearnOpenGL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/brendel/dev/games/LearnOpenGL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/brendel/dev/games/LearnOpenGL/CMakeFiles /Users/brendel/dev/games/LearnOpenGL//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/brendel/dev/games/LearnOpenGL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named LearnOpenGL

# Build rule for target.
LearnOpenGL: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LearnOpenGL
.PHONY : LearnOpenGL

# fast build rule for target.
LearnOpenGL/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/build
.PHONY : LearnOpenGL/fast

src/classes/camera.o: src/classes/camera.cpp.o
.PHONY : src/classes/camera.o

# target to build an object file
src/classes/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/src/classes/camera.cpp.o
.PHONY : src/classes/camera.cpp.o

src/classes/camera.i: src/classes/camera.cpp.i
.PHONY : src/classes/camera.i

# target to preprocess a source file
src/classes/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/src/classes/camera.cpp.i
.PHONY : src/classes/camera.cpp.i

src/classes/camera.s: src/classes/camera.cpp.s
.PHONY : src/classes/camera.s

# target to generate assembly for a file
src/classes/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/src/classes/camera.cpp.s
.PHONY : src/classes/camera.cpp.s

src/classes/keyboard.o: src/classes/keyboard.cpp.o
.PHONY : src/classes/keyboard.o

# target to build an object file
src/classes/keyboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/src/classes/keyboard.cpp.o
.PHONY : src/classes/keyboard.cpp.o

src/classes/keyboard.i: src/classes/keyboard.cpp.i
.PHONY : src/classes/keyboard.i

# target to preprocess a source file
src/classes/keyboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/src/classes/keyboard.cpp.i
.PHONY : src/classes/keyboard.cpp.i

src/classes/keyboard.s: src/classes/keyboard.cpp.s
.PHONY : src/classes/keyboard.s

# target to generate assembly for a file
src/classes/keyboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/src/classes/keyboard.cpp.s
.PHONY : src/classes/keyboard.cpp.s

src/classes/mouse.o: src/classes/mouse.cpp.o
.PHONY : src/classes/mouse.o

# target to build an object file
src/classes/mouse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/src/classes/mouse.cpp.o
.PHONY : src/classes/mouse.cpp.o

src/classes/mouse.i: src/classes/mouse.cpp.i
.PHONY : src/classes/mouse.i

# target to preprocess a source file
src/classes/mouse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/src/classes/mouse.cpp.i
.PHONY : src/classes/mouse.cpp.i

src/classes/mouse.s: src/classes/mouse.cpp.s
.PHONY : src/classes/mouse.s

# target to generate assembly for a file
src/classes/mouse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/src/classes/mouse.cpp.s
.PHONY : src/classes/mouse.cpp.s

src/classes/shader.o: src/classes/shader.cpp.o
.PHONY : src/classes/shader.o

# target to build an object file
src/classes/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/src/classes/shader.cpp.o
.PHONY : src/classes/shader.cpp.o

src/classes/shader.i: src/classes/shader.cpp.i
.PHONY : src/classes/shader.i

# target to preprocess a source file
src/classes/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/src/classes/shader.cpp.i
.PHONY : src/classes/shader.cpp.i

src/classes/shader.s: src/classes/shader.cpp.s
.PHONY : src/classes/shader.s

# target to generate assembly for a file
src/classes/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/src/classes/shader.cpp.s
.PHONY : src/classes/shader.cpp.s

src/classes/shape.o: src/classes/shape.cpp.o
.PHONY : src/classes/shape.o

# target to build an object file
src/classes/shape.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/src/classes/shape.cpp.o
.PHONY : src/classes/shape.cpp.o

src/classes/shape.i: src/classes/shape.cpp.i
.PHONY : src/classes/shape.i

# target to preprocess a source file
src/classes/shape.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/src/classes/shape.cpp.i
.PHONY : src/classes/shape.cpp.i

src/classes/shape.s: src/classes/shape.cpp.s
.PHONY : src/classes/shape.s

# target to generate assembly for a file
src/classes/shape.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/src/classes/shape.cpp.s
.PHONY : src/classes/shape.cpp.s

src/classes/shapes/cube.o: src/classes/shapes/cube.cpp.o
.PHONY : src/classes/shapes/cube.o

# target to build an object file
src/classes/shapes/cube.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/src/classes/shapes/cube.cpp.o
.PHONY : src/classes/shapes/cube.cpp.o

src/classes/shapes/cube.i: src/classes/shapes/cube.cpp.i
.PHONY : src/classes/shapes/cube.i

# target to preprocess a source file
src/classes/shapes/cube.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/src/classes/shapes/cube.cpp.i
.PHONY : src/classes/shapes/cube.cpp.i

src/classes/shapes/cube.s: src/classes/shapes/cube.cpp.s
.PHONY : src/classes/shapes/cube.s

# target to generate assembly for a file
src/classes/shapes/cube.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/src/classes/shapes/cube.cpp.s
.PHONY : src/classes/shapes/cube.cpp.s

src/classes/texture.o: src/classes/texture.cpp.o
.PHONY : src/classes/texture.o

# target to build an object file
src/classes/texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/src/classes/texture.cpp.o
.PHONY : src/classes/texture.cpp.o

src/classes/texture.i: src/classes/texture.cpp.i
.PHONY : src/classes/texture.i

# target to preprocess a source file
src/classes/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/src/classes/texture.cpp.i
.PHONY : src/classes/texture.cpp.i

src/classes/texture.s: src/classes/texture.cpp.s
.PHONY : src/classes/texture.s

# target to generate assembly for a file
src/classes/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/src/classes/texture.cpp.s
.PHONY : src/classes/texture.cpp.s

src/deps/glad/src/glad.o: src/deps/glad/src/glad.c.o
.PHONY : src/deps/glad/src/glad.o

# target to build an object file
src/deps/glad/src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/src/deps/glad/src/glad.c.o
.PHONY : src/deps/glad/src/glad.c.o

src/deps/glad/src/glad.i: src/deps/glad/src/glad.c.i
.PHONY : src/deps/glad/src/glad.i

# target to preprocess a source file
src/deps/glad/src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/src/deps/glad/src/glad.c.i
.PHONY : src/deps/glad/src/glad.c.i

src/deps/glad/src/glad.s: src/deps/glad/src/glad.c.s
.PHONY : src/deps/glad/src/glad.s

# target to generate assembly for a file
src/deps/glad/src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/src/deps/glad/src/glad.c.s
.PHONY : src/deps/glad/src/glad.c.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/setup.o: src/setup.cpp.o
.PHONY : src/setup.o

# target to build an object file
src/setup.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/src/setup.cpp.o
.PHONY : src/setup.cpp.o

src/setup.i: src/setup.cpp.i
.PHONY : src/setup.i

# target to preprocess a source file
src/setup.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/src/setup.cpp.i
.PHONY : src/setup.cpp.i

src/setup.s: src/setup.cpp.s
.PHONY : src/setup.s

# target to generate assembly for a file
src/setup.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LearnOpenGL.dir/build.make CMakeFiles/LearnOpenGL.dir/src/setup.cpp.s
.PHONY : src/setup.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... LearnOpenGL"
	@echo "... glad"
	@echo "... src/classes/camera.o"
	@echo "... src/classes/camera.i"
	@echo "... src/classes/camera.s"
	@echo "... src/classes/keyboard.o"
	@echo "... src/classes/keyboard.i"
	@echo "... src/classes/keyboard.s"
	@echo "... src/classes/mouse.o"
	@echo "... src/classes/mouse.i"
	@echo "... src/classes/mouse.s"
	@echo "... src/classes/shader.o"
	@echo "... src/classes/shader.i"
	@echo "... src/classes/shader.s"
	@echo "... src/classes/shape.o"
	@echo "... src/classes/shape.i"
	@echo "... src/classes/shape.s"
	@echo "... src/classes/shapes/cube.o"
	@echo "... src/classes/shapes/cube.i"
	@echo "... src/classes/shapes/cube.s"
	@echo "... src/classes/texture.o"
	@echo "... src/classes/texture.i"
	@echo "... src/classes/texture.s"
	@echo "... src/deps/glad/src/glad.o"
	@echo "... src/deps/glad/src/glad.i"
	@echo "... src/deps/glad/src/glad.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/setup.o"
	@echo "... src/setup.i"
	@echo "... src/setup.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

